### ISSUE TITLE
yarn run build 打包失败

### ISSUE THREAD

**Issue by G588** [JabinPeng/pengBlog#18]
Error: Failed to compile with errors.
    at C:\Users\Administrator\Desktop\pengBlog\blog\node_modules\@vuepress\core\lib\node\build\index.js:180:16
    at finalCallback (C:\Users\Administrator\Desktop\pengBlog\blog\node_modules\webpack\lib\MultiCompiler.js:254:12)
    at C:\Users\Administrator\Desktop\pengBlog\blog\node_modules\webpack\lib\MultiCompiler.js:277:6
    at done (C:\Users\Administrator\Desktop\pengBlog\blog\node_modules\neo-async\async.js:2931:13)
    at runCompilers (C:\Users\Administrator\Desktop\pengBlog\blog\node_modules\webpack\lib\MultiCompiler.js:181:48)
    at C:\Users\Administrator\Desktop\pengBlog\blog\node_modules\webpack\lib\MultiCompiler.js:188:7
    at C:\Users\Administrator\Desktop\pengBlog\blog\node_modules\webpack\lib\MultiCompiler.js:270:7
    at finalCallback (C:\Users\Administrator\Desktop\pengBlog\blog\node_modules\webpack\lib\Compiler.js:257:39)
    at C:\Users\Administrator\Desktop\pengBlog\blog\node_modules\webpack\lib\Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Administrator\Desktop\pengBlog\blog\node_module
s\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\Administrator\Desktop\pengBlog\blog\node_modules\tapable\lib\Hook.j
s:154:20)
    at onCompiled (C:\Users\Administrator\Desktop\pengBlog\blog\node_modules\webpack\lib\Compiler.js:271:21)
    at C:\Users\Administrator\Desktop\pengBlog\blog\node_modules\webpack\lib\Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Administrator\Desktop\pengBlog\blog\node_module
s\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\Administrator\Desktop\pengBlog\blog\node_modules\tapable\lib\Hook.j
s:154:20)
    at C:\Users\Administrator\Desktop\pengBlog\blog\node_modules\webpack\lib\Compiler.js:678:31
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by G588** [comment]
我的原因是node版本高了，降到或者重新安装到14.17就好了。
