### ISSUE TITLE
npm i报错

### ISSUE THREAD

**Issue by shkmzzh** [JabinPeng/pengBlog#29]
你好，我拉了你的代码后，npm i 时报错 怎么回事啊

npm ERR! code 1
npm ERR! path D:\pengBlog-master\blog\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: D:\VSC\node.exe D:\pengBlog-master\blog\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= 
--libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'D:\\VSC\\node.exe',
npm ERR! gyp verb cli   'D:\\pengBlog-master\\blog\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.15.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\pengBlog-master\blog\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\pengBlog-master\blog\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\pengBlog-master\blog\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\pengBlog-master\blog\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\pengBlog-master\blog\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\pengBlog-master\blog\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\pengBlog-master\blog\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\pengBlog-master\blog\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\pengBlog-master\blog\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\pengBlog-master\blog\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\pengBlog-master\blog\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\pengBlog-master\blog\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\pengBlog-master\blog\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\pengBlog-master\blog\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\pengBlog-master\blog\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\pengBlog-master\blog\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\pengBlog-master\blog\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\pengBlog-master\blog\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\pengBlog-master\blog\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\pengBlog-master\blog\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\pengBlog-master\blog\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\pengBlog-master\blog\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\pengBlog-master\blog\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\pengBlog-master\blog\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python". checking python launcher
npm ERR! gyp verb could not find "python". guessing location
npm ERR! gyp verb ensuring that file exists: C:\Python27\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (D:\pengBlog-master\blog\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (D:\pengBlog-master\blog\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (D:\pengBlog-master\blog\node_modules\graceful-fs\polyfills.js:306:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "D:\\VSC\\node.exe" "D:\\pengBlog-master\\blog\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd D:\pengBlog-master\blog\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.15.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\86158\AppData\Local\npm-cache\_logs\2022-08-25T07_53_25_107Z-debug-0.log
PS D:\pengBlog-master\blog>

**Comment by JabinPeng** [comment]
可能是你node版本高了 尝试一下降版本在试试

**Comment by 1617428415** [comment]
我的也是这个错 楼主怎么解决的

**Comment by fengchuanlin** [comment]
npm run dev 报错是怎么回事呀   我换了三个nodejs的版本了还是一样诶
 报错信息：
npm ERR! Missing script: "dev"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fengchuanlin/.npm/_logs/2022-12-02T11_12_30_464Z-debug-0.log
